# This is a basic workflow to help you get started with Actions

name: Greet New Contributors

on: [pull_request, issues]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hi @${{ github.actor }}, thanks for finding this issue. Someone from development team will soon help you out."
          pr-message: "Hey @${{ github.actor }}, thanks for opening this pull request."
